site_name: rs_datasets

repo_name: 'GitHub'
repo_url: 'https://github.com/Darel13712/rs_datasets'

theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light-blue'
  font:
    text: 'Roboto'
    code: 'Menlo'
  icon:
    logo: 'material/star'

markdown_extensions:
  - admonition
  - codehilite
  - footnotes

extra:
  social:
    - icon: 'fontawesome/brands/github'
      link: 'https://github.com/Darel13712/rs_datasets'